exercise1::users:
    'Trap': 
      ensure:     'present'
      groups:     'Andrews_pGroup'
      home:       '/home/Trap'
      managehome: 'true'
      name:       'Trap'
      uid:         1010
      password:    $6$9X2uKbzKuaujN9.9$0uqotfz9UhD6LzL7TTTOn9J.k9lkwavqCoXIbmu.5o1E9Y/ZtWiI0MD0UND864AG/moIw9SvBqWhoL1/qKNiY/
    'Andrewp': 
      ensure:     'present'
      groups:     'Andrews_pGroup'
      home:       '/home/Andrewp'
      managehome: 'true'
      name:       'Andrewp'
      uid:         1009
      password:    $6$U0b/DJOZAySoFsFS$wLJruNePXgcxM6T6z6Bm0wP8o6/P9q9d3x3ut.AHqlyjWO3DsKGXlisK7wAU1a8j/f4jW0EtBD6ag5x2mDbk8/
    'Miltonp': 
      ensure:     'present'
      groups:     'Andrews_pGroup'
      home:       '/home/Miltonp'
      managehome: 'true'
      name:       'Miltonp'
      uid:         1011
      password:    $6$5Rv3c6S8OJE2MMWg$febzr3nA53bQeKr4lpgxl.mthXNfGJkfE57Rp6q4hTORjDvl/qLqtAi4lKeaHNXRcBS6MRDFHVIDycz.iLW5K0
exercise1::directories:
    '/exercise':
      ensure:      'directory'
      owner:       'Andrewp'
      group:       'Andrews_pGroup'
      mode:        0775
    '/exercise2':
      ensure:      'directory'
      owner:       'Andrewp'
      group:       'Andrews_pGroup'
      mode:        0775
exercise1::groups:
    'Andrews_pGroup':
      ensure:      'present'
      name:        'Andrews_pGroup'
      gid:         2021           
exercise1::nfsserver:
    '/exercise':
      ensure:                 'mounted'
      clients:                '192.168.1.233(rw,sync)'
